-- 코드를 작성해주세요
WITH UNIQUE_PARENT_ITEMS AS (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
) 

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN(
    SELECT PARENT_ITEM_ID 
    FROM UNIQUE_PARENT_ITEMS
    ) 
ORDER BY ITEM_ID DESC