-- 코드를 입력하세요
SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES AS FAVORITES
FROM REST_INFO AS ri
WHERE ri.FAVORITES = (
    SELECT MAX(ri2.FAVORITES) 
    FROM REST_INFO AS ri2
    WHERE ri2.FOOD_TYPE = ri.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC