-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME, a.TOTAL_SALES
FROM (SELECT WRITER_ID, PRICE, SUM(PRICE) AS TOTAL_SALES 
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
     )AS a
JOIN USED_GOODS_USER AS b ON a.WRITER_ID=b.USER_ID
WHERE a.TOTAL_SALES>=700000
GROUP BY a.WRITER_ID
ORDER BY TOTAL_SALES