SELECT 
  YEAR(d.DIFFERENTIATION_DATE) AS YEAR,
  (   SELECT MAX(e.SIZE_OF_COLONY)
     FROM ECOLI_DATA e
    WHERE YEAR(e.DIFFERENTIATION_DATE) = YEAR(d.DIFFERENTIATION_DATE)
  )
  - d.SIZE_OF_COLONY AS YEAR_DEV,
  d.ID
FROM ECOLI_DATA d
ORDER BY YEAR, YEAR_DEV;
