-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK AS a
JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
      FROM BOOK_SALES
      WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
      GROUP BY BOOK_ID
     ) AS b ON b.BOOK_ID = a.BOOK_ID
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY